version: "3.0"
networks:
  laravel:

services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - "8088:80"
    volumes:
      - ./backend:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql
    networks:
      - laravel

  mysql:
    image: mysql:5.7.31
    container_name: mysql
    restart: unless-stopped
    tty: true
    ports:
      - "4306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: cec
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: admin
      SERVICE_NAME: mysql
      SERVICE_TAGS: dev
    networks:
      - laravel

  php:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: php
    volumes:
      - ./backend:/var/www/html
    ports:
      - "9000:9000"
    networks:
      - laravel
  composer:
    image: composer:latest
    container_name: composer
    volumes:
      - ./backend:/var/www/html
    working_dir: /var/www/html
    networks:
      - laravel

  npm:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: npm
    ports:
      - "4200:4200"
    volumes:
      - ./frontend:/app
    # working_dir: /app
    # entrypoint: ["npm"]
    networks:
      - laravel

  artisan:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: artisan
    volumes:
      - ./backend:/var/www/html
    depends_on:
      - mysql
    working_dir: /var/www/html
    entrypoint: ["php", "/var/www/html/artisan"]
    networks:
      - laravel
