
FROM node:14.5.0-alpine
LABEL maintainer="tzalejo@gmail.com"
LABEL version="1.1"
RUN npm install -g @angular/cli && npm cache clean --force
WORKDIR /app
COPY frontend/package.json frontend/package-lock.json ./
RUN npm install
EXPOSE ${NPM_PORT_CONTAINER}
COPY frontend/ .
CMD [ "ng", "serve","--host", "0.0.0.0" ]
